Repository nextcloud-libraries/nextcloud-dialogs, pull requests merged in 2020-03, with the labels that each got.

#94 Make the Toastify selector configurable
  lib/toast.ts
Labels: enhancement

#95 Make the body element the default Toast selector
  lib/toast.ts
Labels: bug

#105 widen versions and update dependencies
  package-lock.json
  package.json
Labels: dependencies
