Repository nextcloud-libraries/nextcloud-dialogs, pull requests merged in 2020-08, with the labels that each got.

#106 Add Undo method & translations
  .github/workflows/l10n.yml
  .github/workflows/node.yml
  .github/workflows/transifex.yml
  .travis.yml
  build/extract-l10n.js
  l10n/fr.pot
  l10n/messages.pot
  lib/filepicker.ts
  lib/index.ts
  lib/l10n.js
  lib/toast.ts
  lib/toastify.d.ts
  package-lock.json
  package.json
  rollup.config.js
  styles/close.svg
  styles/toast.scss
  tsconfig.json
Labels: enhancement

#166 Bundle toastify and transpile it
  .gitattributes
  package-lock.json
  package.json
  rollup.config.js
Labels: bug, dependencies

#177 Fix scss import
  README.md
Labels: documentation

#178 Fix permanent displaying
  README.md
  l10n/messages.pot
  lib/toast.ts
Labels: bug, documentation

#183 Fix more SCSS import hints
  README.md
Labels: bug
