Repository nextcloud-libraries/nextcloud-dialogs, pull requests merged in 2023-08, with the labels that each got.

#878 Implement Vue based Dialogs especially the FilePicker
  .eslintrc.json
  babel.config.js
  l10n/messages.pot
  lib/components/DialogBase.vue
  lib/components/DialogButton.vue
  lib/components/FilePicker/FileList.scss
  lib/components/FilePicker/FileList.vue
  lib/components/FilePicker/FileListRow.vue
  lib/components/FilePicker/FilePicker.vue
  lib/components/FilePicker/FilePickerBreadcrumbs.vue
  lib/components/FilePicker/FilePickerNavigation.vue
  lib/components/FilePicker/LoadingTableRow.vue
  lib/filepicker.ts
  lib/index.ts
  lib/l10n.ts
  lib/legacy.ts
  lib/toast.ts
  lib/toastify.d.ts
  lib/usables/dav.ts
  lib/usables/mime.ts
  lib/vue-shims.d.ts
  package-lock.json
  package.json
  rollup.config.js
  tsconfig.json
  vite.config.ts
Labels: 3. to review

#879 chore: Prepare first beta release with FilePicker 4.2.0-beta.1
  .github/workflows/changelog-generate.yml
  CHANGELOG.md
  README.md
  package-lock.json
  package.json
Labels: 3. to review

#881 fix(FilePicker): Fix design review comments about column alignment
  lib/components/FilePicker/FileList.scss
  lib/components/FilePicker/FileList.vue
  lib/components/FilePicker/FileListRow.vue
Labels: 3. to review

#880 fix(FilePicker): Adjust color of placeholder skeletons
  lib/components/FilePicker/LoadingTableRow.vue
Labels: 3. to review

#882 FilePicker: Navigation and filter should be on separate rows on mobile
  l10n/messages.pot
  lib/components/DialogBase.vue
  lib/components/FilePicker/FilePicker.vue
  lib/components/FilePicker/FilePickerNavigation.vue
Labels: 3. to review

#883 chore: Prepare bugfix release 4.2.0-beta.2
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#889 fix(stable4): Revert nextcloud-vue to version 7.12 to support Nextcloud 27
  README.md
  l10n/messages.pot
  lib/components/FilePicker/FileListRow.vue
  lib/components/FilePicker/NcDatetime.vue
  package-lock.json
  package.json
Labels: 3. to review

#891 docs(README): Add version compatibility section
  README.md
Labels: 3. to review

#893 fix(FilePicker): Request `oc:size` property for showing the file size
  lib/usables/dav.ts
Labels: bug, 3. to review, 🍁 2023-Autumn

#894 [stable4] Backport of the breadcrumbs new button PR
  l10n/messages.pot
  lib/components/DialogBase.vue
  lib/components/FilePicker/FilePickerBreadcrumbs.vue
  lib/window.d.ts
Labels: backport-request, 3. to review

#896 FilePickerBuilder: Allow to add custom buttons and use shipped picker
  lib/filepicker.ts
Labels: 3. to review

#898 [stable4] Allow to add custom buttons and use shipped picker
  lib/filepicker.ts
Labels: 3. to review, 🍁 2023-Autumn

#899 FilePicker: Ensure only the file table is scrolled
  l10n/messages.pot
  lib/components/DialogBase.vue
  lib/components/FilePicker/FileList.vue
  lib/components/FilePicker/FilePicker.vue
Labels: 3. to review, 🍁 2023-Autumn

#901 [stable4] Only scroll file table and not the container
  l10n/messages.pot
  lib/components/DialogBase.vue
  lib/components/FilePicker/FileList.vue
  lib/components/FilePicker/FilePicker.vue
Labels: 3. to review, 🍁 2023-Autumn

#902 chore: Prepare 4.2.0-beta.3
  CHANGELOG.md
Labels: 3. to review

#903 fix(FilePicker): Fix exported typings and cleanup file picker files
  l10n/messages.pot
  lib/components/DialogButton.vue
  lib/components/FilePicker/FileList.vue
  lib/components/FilePicker/FileListRow.vue
  lib/components/FilePicker/FilePicker.vue
  lib/components/FilePicker/FilePickerBreadcrumbs.vue
  lib/components/FilePicker/FilePickerNavigation.vue
  lib/components/FilePicker/index.ts
  lib/components/types.ts
  lib/index.ts
  lib/l10n.ts
  lib/legacy.ts
  lib/toast.ts
  lib/utils/dialogs.ts
  lib/utils/l10n.ts
Labels: 3. to review

#907 fix(FilePicker): Fix exported typings and cleanup file picker files
  l10n/messages.pot
  lib/components/DialogButton.vue
  lib/components/FilePicker/FileList.vue
  lib/components/FilePicker/FileListRow.vue
  lib/components/FilePicker/FilePicker.vue
  lib/components/FilePicker/FilePickerBreadcrumbs.vue
  lib/components/FilePicker/FilePickerNavigation.vue
  lib/components/FilePicker/NcDatetime.vue
  lib/components/FilePicker/index.ts
  lib/components/types.ts
  lib/index.ts
  lib/l10n.ts
  lib/legacy.ts
  lib/toast.ts
  lib/utils/dialogs.ts
  lib/utils/l10n.ts
Labels: 3. to review

#904 feat!(FilePicker): Modernize `FilePickerBuilder` to directly make use of the Vue based file picker
  l10n/messages.pot
  lib/filepicker.ts
Labels: enhancement, 3. to review

#905 Drop legacy entry point (only or stable4)
  l10n/messages.pot
  lib/legacy.ts
  vite.config.ts
Labels: 3. to review

#906 Fix documentation generation
  README.md
  l10n/messages.pot
  lib/components/FilePicker/FilePicker.vue
  lib/components/FilePicker/index.ts
  lib/components/types.ts
  lib/filepicker.ts
  lib/index.ts
  lib/toast.ts
  package-lock.json
  package.json
  tsconfig-typedoc.json
Labels: documentation, 3. to review

#909 docs: Fix typedoc generation and improve documentation of exported member
  README.md
  l10n/messages.pot
  lib/components/FilePicker/index.ts
  lib/index.ts
  lib/toast.ts
  package-lock.json
  package.json
  tsconfig-typedoc.json
Labels: 3. to review

#911 chore: Prepare release of 5.0.0-beta.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#918 chore: Update workflows and remove unneeded node ci
  .github/workflows/documentation.yml
  .github/workflows/node-when-unrelated.yml
  .github/workflows/node.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/npm-publish.yml
  .github/workflows/static-pages.yml
Labels: 3. to review

#921 fix(FilePicker): The table height should be max. 100%
  lib/components/FilePicker/FileList.vue
  lib/components/FilePicker/FilePickerBreadcrumbs.vue
Labels: 3. to review

#922 [stable4] The table height should be max. 100%
  lib/components/FilePicker/FileList.vue
  lib/components/FilePicker/FilePickerBreadcrumbs.vue
Labels: 3. to review

#925 fix(FilePickerBuilder): Revert API change on `pick()`
  l10n/messages.pot
  lib/filepicker.ts
Labels: 3. to review

#928 fix(FilePicker): Fix properties of the `new` button in the breadcrumbs
  lib/components/FilePicker/FilePickerBreadcrumbs.vue
Labels: 3. to review, 🍁 2023-Autumn

#927 fix: Add missing defaults to DialogButton
  lib/components/DialogButton.vue
Labels: 3. to review

#930 Add empty content when there are no files
  l10n/messages.pot
  lib/components/FilePicker/FilePicker.vue
Labels: 3. to review

#932 [stable4] feat(FilePicker): Show empty content when there are no files in folder
  l10n/messages.pot
  lib/components/FilePicker/FilePicker.vue
Labels: 3. to review, 🍁 2023-Autumn

#931 feat(FilePicker): Always show file extension as a trailing text part
  lib/components/FilePicker/FileListRow.vue
Labels: backport-request, 3. to review

#933 [stable4] feat(FilePicker): Always show file extension as a trailing text part
  l10n/messages.pot
  lib/components/FilePicker/FileListRow.vue
Labels: 3. to review, 🍁 2023-Autumn

#935 fix(FilePicker): Ensure focus-visible outline is visible for all focusable elements
  lib/components/FilePicker/FileList.vue
  lib/components/FilePicker/FilePicker.vue
  lib/components/FilePicker/FilePickerNavigation.vue
Labels: 3. to review

#936 [stable4] fix(FilePicker): Ensure focus-visible outline is visible for all focusable elements
  lib/components/FilePicker/FileList.vue
  lib/components/FilePicker/FilePicker.vue
  lib/components/FilePicker/FilePickerNavigation.vue
Labels: 3. to review, 🍁 2023-Autumn

#937 fix: The file list should be showed when files are loading
  l10n/messages.pot
  lib/components/FilePicker/FilePicker.vue
Labels: regression, 3. to review

#939 [stable4] fix: The file list should be showed when files are loading
  l10n/messages.pot
  lib/components/FilePicker/FilePicker.vue
Labels: regression, 3. to review, 🍁 2023-Autumn

#929 fix(FilePicker): Do not show checkboxes on single select mode
  lib/components/FilePicker/FileList.vue
  lib/components/FilePicker/FileListRow.vue
Labels: backport-request, 3. to review

#938 feat: Add icons for filepicker and allow reactive button based on current path and selection
  l10n/messages.pot
  lib/components/DialogButton.vue
  lib/components/FilePicker/FilePicker.vue
  lib/components/types.ts
  lib/filepicker.ts
  lib/svg.d.ts
  lib/utils/dialogs.ts
  package-lock.json
  package.json
Labels: enhancement, backport-request, 3. to review

#941 5.0.0-beta.2
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#942 [stable4] Add icons for filepicker and allow reactive button based on current path and selection
  l10n/messages.pot
  lib/components/DialogButton.vue
  lib/components/FilePicker/FilePicker.vue
  lib/components/types.ts
  lib/legacy.ts
  lib/svg.d.ts
  lib/utils/dialogs.ts
  package-lock.json
  package.json
Labels: 3. to review, 🍁 2023-Autumn

#944 chore: Prepare 4.2.0-beta.4
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review, 🍁 2023-Autumn

#945 [stable4] fix(FilePicker): Fix legacy entry point buttons when bundling with webpack
  lib/legacy.ts
Labels: bug, 3. to review

#949 fix: Make file list only sortable by one property at the time
  l10n/messages.pot
  lib/components/FilePicker/FileList.spec.ts
  lib/components/FilePicker/FileList.vue
  lib/components/FilePicker/FileListRow.vue
  package-lock.json
  package.json
  patches/webdav+5.2.3.patch
  vitest.config.ts
Labels: backport-request, 3. to review

#950 feat(FilePickerBuilder): Allow to configure the dialog container element
  l10n/messages.pot
  lib/filepicker.ts
Labels: 3. to review

#951 [stable4] Make file list only sortable by one property at the time
  l10n/messages.pot
  lib/components/FilePicker/FileList.spec.ts
  lib/components/FilePicker/FileList.vue
  lib/components/FilePicker/FileListRow.vue
  package-lock.json
  package.json
  patches/webdav+5.2.3.patch
  vitest.config.ts
Labels: bug, 3. to review, 🍁 2023-Autumn

#934 fix(FilePicker): Fix selecting rows using the keyboard
  README.md
  lib/components/FilePicker/FileList.spec.ts
  lib/components/FilePicker/FileList.vue
  lib/components/FilePicker/FileListRow.spec.ts
  lib/components/FilePicker/FileListRow.vue
  vitest.config.ts
Labels: bug, backport-request, 3. to review

#954 [stable4] Fix FilePicker keyboard handling
  README.md
  l10n/messages.pot
  lib/components/FilePicker/FileList.spec.ts
  lib/components/FilePicker/FileList.vue
  lib/components/FilePicker/FileListRow.spec.ts
  lib/components/FilePicker/FileListRow.vue
  vitest.config.ts
Labels: bug, 3. to review, 🍁 2023-Autumn

#955 [stable4] fix: Make eslint happy
  lib/components/FilePicker/FileList.vue
  lib/components/FilePicker/FileListRow.vue
Labels: bug, 3. to review

#962 fix: Use core preview controller for loading file previews and fallback to MDI icons
  build/extract-l10n.js
  l10n/messages.pot
  lib/components/FilePicker/FileListRow.vue
  lib/components/FilePicker/FilePreview.vue
  lib/usables/preview.spec.ts
  lib/usables/preview.ts
  package-lock.json
  package.json
  vite.config.ts
Labels: bug, 3. to review

#963 fix(FilePickerBuilder): Fix paths returned in Promise by `pick` method
  lib/filepicker.ts
  lib/utils/dialogs.ts
Labels: regression, 3. to review

#969 fix(FilePicker): Only show checkbox skeletons if multiselect was enabled
  lib/components/FilePicker/FileList.vue
  lib/components/FilePicker/LoadingTableRow.vue
Labels: bug, 3. to review

#967 [stable4] Center heading of dialog
  lib/components/DialogBase.vue
  lib/components/FilePicker/FilePickerBreadcrumbs.vue
Labels: bug, 3. to review, 🍁 2023-Autumn

#970 [stable4] fix(FilePicker): Only show checkbox skeletons if multiselect was enabled
  lib/components/FilePicker/FileList.vue
  lib/components/FilePicker/LoadingTableRow.vue
Labels: bug, 3. to review, 🍁 2023-Autumn

#971 Fix styling issues and make the FilePicker height fixed
  lib/components/DialogBase.vue
  lib/components/FilePicker/FileList.vue
  lib/components/FilePicker/FilePicker.vue
  lib/components/FilePicker/FilePickerNavigation.vue
Labels: bug, 3. to review
