Repository nextcloud-libraries/nextcloud-dialogs, pull requests merged in 2023-06, with the labels that each got.

#824 chore: update workflows from templates
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/node.yml
  .github/workflows/npm-publish.yml
Labels: dependencies, automated, 3. to review

#846 Update CI for l10n extraction to use node version from `package.json`
  .github/workflows/l10n.yml
Labels: 3. to review

#845 Fix package exports for Typescript projects
  package.json
Labels: bug, 3. to review

#842 fix: Setup Typescript for node16 resolution of `@nextcloud/l10n`
  lib/index.ts
  lib/l10n.ts
  tsconfig.json
Labels: bug, 3. to review

#844 Pin updated dependencies
  .github/dependabot.yml
  package-lock.json
  package.json
Labels: 3. to review

#843 fix: Make sure dependencies are external
  babel.config.js
  rollup.config.js
Labels: 3. to review

#847 chore: update node engines to next LTS
  package.json
Labels: dependencies, automated, 3. to review

#848 Prepare release of version 4.1.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review
