Repository nextcloud-libraries/nextcloud-dialogs, pull requests merged in 2023-09, with the labels that each got.

#968 [stable4] fix(FilePicker): Reset selected files if the current directory is change
  l10n/messages.pot
  lib/components/FilePicker/FilePicker.vue
Labels: bug, 3. to review, 🍁 2023-Autumn

#966 [stable4] fix(l10n): Extract translations also from vue SFC template attributes
  build/extract-l10n.js
  l10n/messages.pot
Labels: bug, 3. to review, 🍁 2023-Autumn

#982 v4.2.0-beta.5
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#981 5.0.0-beta.3
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#964 fix(FilePicker): Reset selected files if the current directory is changed
  lib/components/FilePicker/FilePicker.vue
Labels: bug, 3. to review

#984 Revert "fix: Patch `webdav` dependency for invalid `exports` field un…
  package-lock.json
  package.json
  patches/webdav+5.2.3.patch
Labels: bug, dependencies, 3. to review

#985 [stable4] Revert "fix: Patch `webdav` dependency for invalid `exports` field un…
  package-lock.json
  package.json
  patches/webdav+5.2.3.patch
Labels: bug, 3. to review

#986 5.0.0-beta.4
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#993 Fix alignment of file list
  lib/components/FilePicker/FileList.scss
  lib/components/FilePicker/FileList.vue
  lib/components/FilePicker/FileListIcon.module.scss
  lib/components/FilePicker/FilePicker.vue
  lib/components/FilePicker/FilePreview.vue
  lib/components/FilePicker/LoadingTableRow.vue
  lib/global.d.ts
  package-lock.json
  package.json
  tsconfig.json
  vitest.config.ts
Labels: bug, 3. to review

#992 fix(FilePicker): Use `search` function from `webdav` package instead of workaround
  lib/usables/dav.spec.ts
  lib/usables/dav.ts
Labels: bug, 3. to review, file picker

#994 [stable4] Fix table alignment
  lib/components/FilePicker/FileList.scss
  lib/components/FilePicker/FileList.vue
  lib/components/FilePicker/FileListIcon.module.scss
  lib/components/FilePicker/FileListRow.vue
  lib/components/FilePicker/FilePicker.vue
  lib/components/FilePicker/LoadingTableRow.vue
  lib/global.d.ts
  package-lock.json
  package.json
  tsconfig.json
  vitest.config.ts
Labels: bug, 3. to review, 🍁 2023-Autumn

#996 [stable4] fix: breadcrumbs grow
  lib/components/FilePicker/FilePickerBreadcrumbs.vue
Labels: bug

#995 [stable4] fix(Dialog): Make the dialog flex column to show headline on top of content
  lib/components/DialogBase.vue
Labels: bug, regression

#997 fix(FilePicker): Ensure file list header is shown on top of scrolled content rows
  lib/components/FilePicker/FileList.vue
Labels: bug, 3. to review

#998 [stable4] fix(FilePicker): Ensure file list header is shown on top of scrolled content rows
  lib/components/FilePicker/FileList.vue
Labels: bug, 3. to review, 🍁 2023-Autumn

#1000 [stable4] Avoid error when not using any custom buttons
  lib/filepicker.ts
Labels: bug

#1007 [stable24] Bring back the default value for legacy file picker
  lib/legacy.ts
Labels: bug, regression, 3. to review

#1008 chore: Prepare 4.2.1 release
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#1015 [stable4] Backport preview generation for FilePicker
  l10n/messages.pot
  lib/components/FilePicker/FileList.vue
  lib/components/FilePicker/FileListRow.vue
  lib/components/FilePicker/FilePreview.vue
  lib/index.ts
  lib/usables/preview.ts
  package-lock.json
  package.json
  vite.config.ts
Labels: enhancement, 3. to review, file picker
