Repository nextcloud-libraries/nextcloud-dialogs, pull requests merged in 2023-10, with the labels that each got.

#1034 v5.0.0-beta.5
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#1043 chore: Switch to v8 as code coverage provider, reduces the dependencies
  .github/workflows/node-test.yml
  package-lock.json
  package.json
  vitest.config.ts
Labels: dependencies, 3. to review

#1058 fix: Swap sort icons
  lib/components/FilePicker/FileList.vue
Labels: bug, 3. to review

#1059 [stable4] fix: Swap sort icons
  lib/components/FilePicker/FileList.vue
Labels: bug, 3. to review

#973 Get files app config and use it for the file picker
  lib/components/FilePicker/FileList.spec.ts
  lib/components/FilePicker/FileList.vue
  lib/components/FilePicker/FileListRow.spec.ts
  lib/components/FilePicker/FilePicker.vue
  lib/components/FilePicker/FilePreview.vue
  lib/composables/dav.spec.ts
  lib/composables/dav.ts
  lib/composables/filesSettings.spec.ts
  lib/composables/filesSettings.ts
  lib/composables/filesViews.spec.ts
  lib/composables/mime.spec.ts
  lib/composables/mime.ts
  lib/composables/preview.spec.ts
  lib/composables/preview.ts
  package-lock.json
  package.json
Labels: enhancement, 3. to review, 🍁 2023-Autumn

#1072 fix(FilePicker): Make the validity strings more specific
  l10n/messages.pot
  lib/components/FilePicker/FilePickerBreadcrumbs.vue
Labels: bug, 3. to review

#1070 Fix package and add separate filepicker entry point
  .github/workflows/lint-stylelint.yml
  README.md
  lib/filepicker-builder.ts
  lib/filepicker.ts
  lib/index.ts
  package-lock.json
  package.json
  vite.config.ts
  vitest.config.ts
Labels: bug, 3. to review
