Repository nextcloud-libraries/nextcloud-dialogs, pull requests merged in 2023-11, with the labels that each got.

#1095 FilePicker: Signal folder creation to files app
  lib/components/FilePicker/FilePicker.vue
  lib/composables/dav.ts
  package-lock.json
  package.json
Labels: enhancement, 3. to review, file picker

#1096 Release 4.2.2
  CHANGELOG.md
  lib/components/FilePicker/FilePicker.vue
  package-lock.json
  package.json
Labels: 3. to review

#1101 fix: Use `NcDialog` instead of custom dialog component now that it is upstreamed
  lib/components/DialogBase.vue
  lib/components/DialogButton.vue
  lib/components/FilePicker/FilePicker.vue
  lib/components/types.ts
  package-lock.json
  package.json
Labels: enhancement, dependencies, 3. to review

#1102 Update `@nextcloud/vue` to stable and release v5.0.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#1113 fix(FilePicker): Listen on `update:open` rather than `closed` event from `NcDialog`
  lib/components/FilePicker/FilePicker.vue
  package-lock.json
  package.json
Labels: bug, regression, 3. to review

#1114 chore: Update `@nextcloud/vue`
  package-lock.json
  package.json
Labels: 3. to review

#1115 chore: Release 5.0.2
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#1120 fix(FilePicker): `cropImagePreviews` is now provided as a prop in FilePreview
  lib/components/FilePicker/FileListRow.vue
  lib/components/FilePicker/FilePreview.vue
  lib/composables/filesSettings.ts
Labels: bug, regression, 3. to review

#1121 fix(FilePicker): On button click also emit the current directory if `allowPickDirectory` is set to true
  lib/components/FilePicker/FilePicker.vue
Labels: bug, 3. to review

#1128 fix(build): include ?raw data to bundle
  package-lock.json
  package.json
  vite.config.ts
Labels: bug
