Repository nextcloud-libraries/nextcloud-dialogs, pull requests merged in 2024-01, with the labels that each got.

#1152 chore: update workflows from templates
  .github/workflows/documentation.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node-test.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/npm-publish.yml
Labels: dependencies, automated, 3. to review

#1165 fix(FilePicker): Use `Node::path` for current path fixing an clicking favorite folders
  lib/components/FilePicker/FileList.vue
Labels: bug, 3. to review

#1166 enh(FilePickerBuilder): Change error thrown when FilePicker is closed
  lib/filepicker-builder.ts
Labels: enhancement, 3. to review

#1167 [stable4] fix(FilePicker): Use Node::path for current path fixing an clicking favorite folders
  lib/components/FilePicker/FileList.vue
Labels: bug, 3. to review

#1180 Remove unneeded `tab`, `tablist` and `aria-selected` roles from navigation
  l10n/messages.pot
  lib/components/FilePicker/FilePickerNavigation.vue
Labels: 3. to review

#1179 Remove `aria-label` from `<div>`
  l10n/messages.pot
  lib/components/FilePicker/FilePreview.vue
Labels: 3. to review, accessibility

#1192 fix(FilePicker): Stop click event on checkbox column to allow multiselect
  lib/components/FilePicker/FileListRow.spec.ts
  lib/components/FilePicker/FileListRow.vue
Labels: bug, 3. to review

#1193 fix(FilePicker): Adjust checkbox position
  lib/components/FilePicker/FileList.scss
Labels: bug, 3. to review

#1191 fix(FilePicker): Improve choose button text when selecting multiple
  l10n/messages.pot
  lib/filepicker-builder.ts
Labels: enhancement, 3. to review

#1197 chore: Prepare 5.1.0 release
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#1196 chore: Update dependencies for stable4
  package-lock.json
  package.json
Labels: 3. to review

#1198 fix(FilePicker): Export `FilePickerClosed` error
  lib/index.ts
Labels: 3. to review

#1199 chore: Prepare 4.2.3 release
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#1207 fix(FilePicker): Stop default close event in case of button press
  lib/components/FilePicker/FilePicker.vue
Labels: bug, 3. to review

#1210 chore: Prepare 5.1.1 release
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#1217 [stable4] fix(l10n): Update translations from main branch
  l10n/ast.pot
  l10n/ca.pot
  l10n/cs_CZ.pot
  l10n/de.pot
  l10n/de_DE.pot
  l10n/es.pot
  l10n/fr.pot
  l10n/id.pot
  l10n/is.pot
  l10n/it.pot
  l10n/nb_NO.pot
  l10n/nl.pot
  l10n/pl.pot
  l10n/pt_BR.pot
  l10n/ro.pot
  l10n/ru.pot
  l10n/sr.pot
  l10n/sv.pot
  l10n/tr.pot
  l10n/uk.pot
Labels: bug, 3. to review

#1220 chore: Prepare 4.2.4 release
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review
