Repository nextcloud-libraries/nextcloud-dialogs, pull requests merged in 2024-04, with the labels that each got.

#1287 fix(FilePicker): Request all default file props (incl. file id)
  lib/composables/dav.ts
Labels: bug, 3. to review

#1298 chore: Prepare 5.2.1 release
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#1297 feat: Provide generic dialogs previously provided by `OC.dialogs`
  lib/components/GenericDialog.vue
  lib/components/types.ts
  lib/dialogs.ts
  lib/index.ts
  lib/utils/dialogs.ts
Labels: enhancement, 3. to review

#1302 fix: Close actions after creating directory and enter it automatically
  lib/components/FilePicker/FilePicker.vue
  lib/components/FilePicker/FilePickerBreadcrumbs.vue
Labels: bug, 3. to review

#1299 fix: Fix incorrect directory contents when navigating quickly
  lib/composables/dav.spec.ts
  lib/composables/dav.ts
  package-lock.json
  package.json
  vite.config.ts
Labels: bug, 3. to review

#1308 chore: v5.3.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review
