Repository nextcloud-libraries/nextcloud-dialogs, pull requests merged in 2024-11, with the labels that each got.

#1448 [main] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#1478 feat: Rate-limit image previews
  lib/components/FilePicker/FilePreview.vue
  lib/composables/preview.ts
  lib/utils/imagePreload.ts
  package-lock.json
  package.json
  test/setup.ts
  vite.config.ts
  vitest.config.ts
Labels: enhancement, backport-request, 3. to review

#1488 chore: Prepare release of 5.3.8
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#1489 chore: Prepare v6.0.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review
