Repository nextcloud-libraries/nextcloud-dialogs, pull requests merged in 2024-02, with the labels that each got.

#1226 fix: Pin nextcloud/files to last resolved version
  package-lock.json
  package.json
Labels: 3. to review

#1227 chore: v4.2.5
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#1241 fix(FilePicker): Allow using on public shares
  l10n/messages.pot
  lib/components/FilePicker/FilePicker.vue
  lib/components/FilePicker/FilePickerNavigation.vue
  lib/composables/dav.spec.ts
  lib/composables/dav.ts
  lib/composables/filesSettings.spec.ts
  lib/composables/filesSettings.ts
  lib/composables/isPublic.ts
  lib/composables/views.spec.ts
  lib/composables/views.ts
  package-lock.json
  package.json
Labels: bug, 3. to review

#1243 [stable4] fix public shares
  lib/components/FilePicker/FilePicker.vue
  lib/components/FilePicker/FilePickerNavigation.vue
  lib/usables/dav.ts
  lib/usables/isPublic.ts
Labels: bug, 3. to review, 🍁 2023-Autumn

#1244 chore: Prepare 5.1.2 release
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review
