Repository nextcloud-libraries/nextcloud-dialogs, pull requests merged in 2024-08, with the labels that each got.

#1414 [main] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#1419 fix!: Revert breaking changes in DAV endpoint handling
  CHANGELOG.md
  lib/composables/dav.spec.ts
  lib/composables/dav.ts
  lib/composables/filesSettings.spec.ts
  lib/toast.ts
  lib/utils/dav.spec.ts
  lib/utils/dialogs.ts
  package-lock.json
  package.json
  tsconfig.json
Labels: bug, regression, 3. to review

#1420 chore: Release v6.0.0 for Nextcloud 29+
  CHANGELOG.md
  package-lock.json
  package.json
  tsconfig.json
Labels: 3. to review

#1422 fix: Mention supported versions in README
  README.md
Labels: 3. to review

#1428 fix: Fetch also current folder in DAV
  lib/composables/dav.ts
Labels: bug, 3. to review

#1429 chore: Prepare v5.3.7
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#1436 [main] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review
