Repository nextcloud-libraries/nextcloud-dialogs, pull requests merged in 2024-03, with the labels that each got.

#1261 feat: allow to disable file picker navigation
  lib/components/FilePicker/FilePicker.vue
  lib/components/FilePicker/FilePickerNavigation.vue
  lib/filepicker-builder.ts
  package-lock.json
  package.json
Labels: enhancement, 3. to review

#1262 fix(FilePicker): Adjust margin of view-selector to be consistent with…
  lib/components/FilePicker/FilePickerNavigation.vue
Labels: bug, 3. to review

#1276 [main] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review
