Repository nextcloud-libraries/nextcloud-dialogs, pull requests merged in 2025-05, with the labels that each got.

#1715 refactor!: Migrate to vue3
  .eslintrc.json
  README.md
  lib/components/FilePicker/FileList.spec.ts
  lib/components/FilePicker/FileList.vue
  lib/components/FilePicker/FileListRow.spec.ts
  lib/components/FilePicker/FileListRow.vue
  lib/components/FilePicker/FilePicker.vue
  lib/components/FilePicker/FilePickerBreadcrumbs.vue
  lib/components/FilePicker/FilePickerNavigation.vue
  lib/components/FilePicker/FilePreview.vue
  lib/components/FilePicker/LoadingTableRow.vue
  lib/components/FilePicker/index.ts
  lib/components/GenericDialog.vue
  lib/components/types.ts
  lib/composables/dav.spec.ts
  lib/composables/dav.ts
  lib/composables/filesSettings.spec.ts
  lib/composables/filesViews.spec.ts
  lib/dialogs.ts
  lib/filepicker-builder.ts
  lib/filepicker.ts
  lib/index.ts
  lib/utils/l10n.ts
  lib/vue-icons.d.ts
  lib/vue-shims.d.ts
  package-lock.json
  package.json
  tsconfig.json
  vite.config.ts
Labels: enhancement, 3. to review

#1742 ci: add dependabot and npm audit fix for stable6
  .github/dependabot.yml
  .github/workflows/npm-audit-fix.yml
Labels: 3. to review

#1752 refactor: do not use Node internals but `@nextcloud/paths` package
  lib/composables/dav.ts
  lib/filepicker-builder.ts
  lib/utils/dav.ts
  package-lock.json
  package.json
Labels: 3. to review

#1751 chore: prepare release of v7.0.0-rc.0
  CHANGELOG.md
Labels: 3. to review

#1759 [stable6] feat: add guest auth prompt component
  l10n/messages.pot
  lib/components/PublicAuthPrompt.vue
  lib/index.ts
  lib/public-auth.ts
  package-lock.json
  package.json
Labels: backport-request, 3. to review

#1775 fix(FilePickerBuilder): correctly return array / plain value depending on multiselect
  lib/filepicker-builder.ts
Labels: bug, backport-request, 3. to review

#1774 refactor: adjust code to comply with code style (again)
  .github/workflows/lint-eslint.yml
  lib/components/PublicAuthPrompt.vue
  lib/index.ts
  lib/public-auth.ts
  package.json
Labels: 3. to review
