Repository nextcloud-libraries/nextcloud-dialogs, pull requests merged in 2025-01, with the labels that each got.

#1502 [main] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#1545 fix(files): Add encrypted icon for end-to-end encrypted folder
  lib/components/FilePicker/FilePreview.vue
Labels: bug, 3. to review

#1554 feat(toast): add loading toast
  REUSE.toml
  lib/index.ts
  lib/toast.ts
  styles/loader.svg
  styles/toast.scss
Labels: enhancement, 3. to review

#1552 [stable5] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#1555 chore: 6.1.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#1559 fix(toast): loading svg
  lib/toast.ts
  styles/toast.scss
Labels: bug, 3. to review

#1569 chore: 6.1.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review
