Repository nextcloud-libraries/nextcloud-dialogs, pull requests merged in 2025-04, with the labels that each got.

#1685 [stable5] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#1726 [main] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#1730 feat: allow picking files using the Nextcloud Nodes API
  lib/filepicker-builder.ts
Labels: enhancement, 3. to review

#1733 fix(file-picker): align folder design with Nextcloud files app
  lib/components/FilePicker/FileListIcon.module.scss
  lib/components/FilePicker/FilePreview.vue
Labels: bug, 3. to review

#1732 fix: the nc-vue dialogs function module is called `dialog` not `dialogs`
  lib/dialogs.ts
  lib/filepicker-builder.ts
  lib/utils/dialogs.ts
  lib/vue-shims.d.ts
Labels: bug, 3. to review

#1734 perf: do not pre-load folder mime icon
  lib/composables/preview.ts
Labels: bug, 3. to review

#1736 chore: update workflows from organization
  .github/workflows/command-l10n-update.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/documentation.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node-test.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/npm-publish.yml
  .github/workflows/reuse.yml
Labels: 3. to review
